### ISSUE TITLE
pip install ppd fails for python 3.10.4 and 3.10.8 on macOS 12.6 (Monterey)

### ISSUE THREAD

**Issue by bwagner** [jarun/pdd#24]
`pip install ppd` fails for python 3.10.4 and 3.10.8 on macOS 12.6 (Monterey) with `FileNotFoundError: [Errno 2] No such file or directory: 'pdd'`

Workaround: Downloading the zip-file and installing with `pip install pdd-master.zip` succeeds.

Transcript:
```
pip install pdd
Collecting pdd
  Using cached pdd-1.6.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/88/ycwg1tqn27q6xc2h7whfx8d00000gp/T/pip-install-3zwkde0k/pdd_39109a313a5d4095bced56f61a637d7d/setup.py", line 9, in <module>
          shutil.copyfile('pdd', 'pdd.py')
        File "/Users/.../.asdf/installs/python/3.10.8/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 254, in copyfile
          with open(src, 'rb') as fsrc:
      FileNotFoundError: [Errno 2] No such file or directory: 'pdd'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jarun** [comment]
I can repro it. Somehow the package in PyPi has the file `pdd.py` and not `pdd`.

Will have to fix this in the next release.

**Comment by jarun** [comment]
Released pdd v1.7 - https://github.com/jarun/pdd/releases/tag/v1.7

Can you please test and confirm?

**Comment by bwagner** [comment]
Tested successfully on 3.10.8.
Thank you!

**Comment by jarun** [comment]
Thanks a lot!
